### ISSUE TITLE
[建议]JNI静态注册改为动态注册

### ISSUE THREAD

**Issue by xmhwws** [amimo/dcc#10]
大佬，有没有考虑过将JNI静态注册改为动态注册？

**Comment by xmhwws** [comment]
`JNI静态注册`程序运行效率低，因为初次调用native函数时需要根据根据函数名在JNI层中搜索对应的本地函数，然后建立对应关系，这个过程比较耗时；
防护的话，通过ollvm应该可以加密字符串。能增加一些防护强度。也不会使逆向者一下子（静态注册比较明显）就hook对应的方法，得到参数和返回值。

**Comment by amimo** [comment]
> `JNI静态注册`程序运行效率低，因为初次调用native函数时需要根据根据函数名在JNI层中搜索对应的本地函数，然后建立对应关系，这个过程比较耗时；

我觉得一切效率问题在在满是JNI反射的代码里面都不是问题.


> 防护的话，通过ollvm应该可以加密字符串。能增加一些防护强度。也不会使逆向者一下子（静态注册比较明显）就hook对应的方法，得到参数和返回值。

这个倒是可以稍微增加一点点难度,但是通过hook JNI RegisterNatives也是马上可以搞定的.

**Comment by xmhwws** [comment]
> 我觉得一切效率问题在在满是JNI反射的代码里面都不是问题.

我觉得你是正确的

> 这个倒是可以稍微增加一点点难度,但是通过hook JNI RegisterNatives也是马上可以搞定的.

百尺竿头更进一步？
大多数情况下，和逆向者打的是一场心理战。
仅仅只是建议。

**Comment by amimo** [comment]
我觉得没有什么必要.
直接让他们看到Native代码,说不准还能直接把他们唬住了:-)

**Comment by amimo** [comment]
最新代码已支持动态注册
