### ISSUE TITLE
我有一些问题，希望能够得到解决，谢谢！

### ISSUE THREAD

**Issue by wxk6b1203** [amimo/dcc#12]
1. ./gradlew assembleDebug 得到的结果可以在手机上运行，但通过Android studio调试会崩溃。也许是我不熟悉安卓的开发流程？
2. 由问题1，我如何知道经过
```
python3 dcc.py tests/demo-java/app/build/outputs/apk/debug/app-debug.apk --source-dir=tests/demo-c/app/src/main/ --no-build
```
运行的不是demo-c中原有的Java方法，而是新的c方法？

**Comment by amimo** [comment]
> 运行的不是demo-c中原有的Java方法，而是新的c方法？
demo-c里边没有java方法,安装demo-c生成的apk,运行的肯定都是c方法.

你也可以直接运行如下命令,生成的demo.apk就是加固后的.
```sh
python3 dcc.py tests/demo-java/app/build/outputs/apk/debug/app-debug.apk -o demo.apk
```

**Comment by wxk6b1203** [comment]
我从加固后的apk反编译出来，确实包含了nc.so,但其中也包括了一些写了java文件的smali
![image](https://user-images.githubusercontent.com/8924149/69960516-a21d2580-1544-11ea-86d3-c53b067313d8.png)
我清楚直接出的apk是没方法的，
我不太理解，这里的调用情况为如何。恕愚钝，我不太了解其中的执行情况😅，能否给些指点或建议？谢谢谢谢！！！

**Comment by amimo** [comment]
你对比一下加固前后的同名smali文件

**Comment by wxk6b1203** [comment]
晓得了，谢谢大佬😥😘
