### ISSUE TITLE
请问TSSA -> CSSA,然后给PHI相关变量分配相同名字来消除PHI相关的逻辑在那里

### ISSUE THREAD

**Issue by liowmark** [amimo/dcc#2]
你好我看了你代码，但是我找不到TSSA -> CSSA 这一步的逻辑在哪，能给我标注下吗。

**Comment by liowmark** [comment]
我分析了流程好像就直接dvm字节码按照<Simple and Efficient Construction of Static Single Assignment Form>直接翻译成IR，然后就直接用相同名字（根据寄存器编号跟参数类型）消去Phi，没有TSSA转CSSA的步骤，是不是dvm的字节码直接翻译过来的实际上已经符合(CSSA)。

**Comment by amimo** [comment]
是没有TSSA到CSSA的过程。 对于归约CFG，转出来的就是CSSA；对于不可归约的CFG，按我的理解，只要PHI相关资源活跃不冲突，同样可以给他们分配相同的名字的消除PHI。
刚转出来，没有经过任何优化的PHI相关资源，我理解也是不会冲突的，如：
r0_2 = phi(r0_0, r0_1)
r0_0, r0_1, v0_2 都来源于同一个寄存器r0。既然他们能分配到同一个寄存器r0，那么他们肯定不会冲突。

对变量进行命名确实是使用寄存器编号和类型。
另外，compiler.py还有个叫verify_phi_operand_type函数，它是用来确保phi相关变量会分配到相同的名称，保证PHI消除是正确的。

**Comment by liowmark** [comment]
thks
