### ISSUE TITLE
demo-c编译错误

### ISSUE THREAD

**Issue by h45251880** [amimo/dcc#20]
Build command failed.
Error while executing process C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\20.1.5948944\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Administrator\Desktop\0\dcc\tests\demo-c\app\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\Administrator\Desktop\0\dcc\tests\demo-c\app\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-19 NDK_OUT=C:/Users/Administrator/Desktop/0/dcc/tests/demo-c/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\Administrator\Desktop\0\dcc\tests\demo-c\app\build\intermediates\ndkBuild\debug\lib C:/Users/Administrator/Desktop/0/dcc/tests/demo-c/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libnc.so}
[armeabi-v7a] Compile++ thumb: nc <= Java_com_test_TestCompiler_MethodCall_manyArgs__IJIJIJIIDFDSICIIBZIIJJIIIII_3_3Ljava_lang_String_2_3Ljava_lang_String_2Ljava_lang_String_2.cpp

make: *** [C:/Users/Administrator/Desktop/0/dcc/tests/demo-c/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/nc/nc/Java_com_test_TestCompiler_MethodCall_manyArgs__IJIJIJIIDFDSICIIBZIIJJIIIII_3_3Ljava_lang_String_2_3Ljava_lang_String_2Ljava_lang_String_2.o] Error 1

**Comment by amimo** [comment]
我也不知道啥问题,windows我测试的很少,都是在linux下开发测试的.

**Comment by h45251880** [comment]
用linux 所有问题都迎刃而解
