### ISSUE TITLE
安装包内其他目录内有不可反编译的.dex文件时会无法加固

### ISSUE THREAD

**Issue by qinlili23333** [amimo/dcc#30]
100%复现方法:随便找一个不是dex的文件改名为xxx.dex塞进apk任意目录

临时解决方法:先把这个不是dex的.dex文件删掉再加固,加固后再塞回来

**Comment by amimo** [comment]
这是apktool的问题,你可以尝试把apktool升级到2.4.1,然后使用"--only-main-classes"参数,只反编译根目录下的dex.
