### ISSUE TITLE
你好，有个问题想请教一下

### ISSUE THREAD

**Issue by 1767523953** [amimo/dcc#37]
我想问一下，这个可不可以使用OLLVM来编译呢？
如果可以的话，那应该如何实现呢？

**Comment by nnjun** [comment]
不是生成好源码了吗，直接用ollvm编译一遍不就好了。

**Comment by amimo** [comment]
理论上可以的。
 * 修改dcc.cfg中的ndk_dir为你的混淆工具链或者把混淆ndk-build加到PAH环境变量
 * 在“project/jni/Application.mk”中新增“NDK_TOOLCHAIN_VERSION”，把它的值设置为你混淆工具链名称
