### ISSUE TITLE
windows10 编译出现几个异常 以及 请教大佬一些关于DCC的事情

### ISSUE THREAD

**Issue by xmhwws** [amimo/dcc#4]
DCC是个很棒的开源项目，但我体验了一下，发现了一些小问题。
如果作者大大有时间的话，请帮忙解惑一下，感激。ヾ(=･ω･=)o

昨晚用ubuntu编译测试demo，测试成功。
今天用windows10编译，就报错了。
各种系统环境已经配置好，NDK r17c，默认pthon3.7。
`python dcc.py tests\demo-java\app\build\outputs\apk\debug\app-debug.apk --source-dir=tests\demo-c\app\src\main\ --no-build`
输出信息：
Traceback (most recent call last):
  File "dcc.py", line 435, in <module>
    dcc_cfg = json.load(fp)
  File "D:\python\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "D:\python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 19 (char 20)

查看dcc.cfg
![d1](https://user-images.githubusercontent.com/42903751/66041596-cd879200-e54c-11e9-85fb-3d4fada93aed.png)
按照网友给的方法，将json.load(fp)改为json.load(fp, strict=False)，没有用。
尝试加上转义符
![d2](https://user-images.githubusercontent.com/42903751/66041831-6d452000-e54d-11e9-9578-d1f889dd3f40.png)
能够正常编译。
大佬，这算bug吗？哭笑

奇怪的so异常：
![异常](https://user-images.githubusercontent.com/42903751/66057871-008d4e00-e56c-11e9-93e0-905dab77fa95.png)

No rule to make target 异常：
![2019-10-02_23-33-22](https://user-images.githubusercontent.com/42903751/66058486-0afc1780-e56d-11e9-9a50-36a30dfd6fdf.png)

以及apk安装后，一运行就闪退。
这个，我想了下，我是直接用dcc.py处理apk，没有加载Native库。
emmmm，是这个原因吗？
是不是先通过反编译，把加载Native库的smali代码添加到合适的位置，再回编译，然后用dcc.py处理apk？

我都怀疑我是bug聚合体质了，苦笑。

还有几个小疑问：
1.Android studio生成的签名文件是`.jks`后缀名，dcc修改哪里，使其自动使用我提供的jks文件进行签名呢？

2.我看大佬你的py中，对filter.txt的处理：
![filter](https://user-images.githubusercontent.com/42903751/66054019-f49e8d80-e565-11e9-8536-88dea43aaf83.png)
以换行符分隔，`#`代表注释，`!`代表不编译后面的类，`=`代表编译=后面的类（不使用正则），句首没有符号代表编译这一行？是这个意思吗？

3.filter.txt里面有下面一段文本：
```
# do not compile constructor
!<clinit|init>
```
这代表着DCC其实是处理相关smali代码，而非java代码？
且DCC是根据方法名的smali代码只处理方法，不处理其他（变量等等）？

4.如果我打算编译的方法内部调用了我禁止编译的方法（举个例子：我禁止编译谷歌gson相关类，但我打算编译的方法内部调用了gson），DCC是如何处理的呢？

5.如果只想编译某个类的特定的那个方法，是不是只要填写那个方法`名`对应的smali代码？
如果只想编译某个类全部方法，只需要填写那个方法类对应的smali代码？

6.能否提供编译其他架构so的接口，就是默认只编译arm的so，通过传参，额外编译指定so？

7.filter.txt里面有下面一段文本：
```
# compile method named onCreate, mostly activity's onCreate
.*;onCreate\(Landroid/os/Bundle;.*
```
onCreate\(Landroid/os/Bundle;我知道，但前面的`.*;`是什么意思？
我没看明白，我反编译了一个apk，它是这样子的：
![2019-10-02_23-59-08](https://user-images.githubusercontent.com/42903751/66060752-c5414e00-e570-11e9-8d22-978efe8dc060.png)
我深深地困惑着。

小疑问不回答也没关系，处理上面的bug比较重要。

最后，非常感谢大佬的DCC，晚安~~~

**Comment by amimo** [comment]
> 能够正常编译。
> 大佬，这算bug吗？哭笑

不算吧.我配置AndroidStudio的ndk.dir的时候,也是需要手动转义.


> 奇怪的so异常：

这个你需要编辑下这个文件
```
vi project/jni/Application.mk
```
把第4行打开,第5行注释掉.

> No rule to make target 异常

这个问题比较奇怪,我感觉可能跟系统有关系,你可以用ubuntu试试,如果ubuntu有问题,那就是bug.我之前测试拼多多的时候遇到过这个库,没发现这个问题.

> 这个，我想了下，我是直接用dcc.py处理apk，没有加载Native库。
> emmmm，是这个原因吗？
> 是不是先通过反编译，把加载Native库的smali代码添加到合适的位置，再回编译，然后用dcc.py处理apk？

应该是的,我测试第三方应用的时候都是手动修改的.在他们Application里面加上加载库代码试试.可以参考下面的代码
```
# direct methods
.method public static constructor <clinit>()V
    .locals 1

    const-string v0, "nc"

    invoke-static {v0}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V

    return-void
.end method
```

疑问
1.你需要使用jarsigner或者apksigner对处理后的apk进行重签名.
2.等号是我测试用的,用于完全匹配某个方法.
3.dcc处理的是dalvik字节码,apktool用于修改字节码,将处理后的方法改为native方法.
4.不支持.你需要禁止编译gson类,自己查找使用他们的所有方法,把他们写到filter里面.
5.参考当前filter.txt,都有对应的写法.
6.你需要编辑下这个文件
```
vi project/jni/Application.mk
```
修改里面的"APP_ABI"配置.
7.filter里面的规则用的都是正则表达式.你可以去了解下.

**Comment by xmhwws** [comment]
Ubuntu18.04.3 LTS

filter.txt内容：
![filter](https://user-images.githubusercontent.com/42903751/66110282-109f3f00-e5f9-11e9-883a-cc651e4f9f07.png)


此时，使用android-ndk-r17c

Application.mk部分内容：
`#APP_ABI := armeabi-v7a arm64-v8a`
APP_ABI := armeabi-v7a
异常：
[ERROR   ] dcc: Compile /home/xi/p/dcc/tests/share/Share-v1.0.apk failed!
Traceback (most recent call last):
  File "dcc.py", line 441, in <module>
    dcc_main(infile, filtercfg, outapk, do_compile, project_dir, source_archive)
  File "dcc.py", line 395, in dcc_main
    copy_compiled_libs(project_dir, decompiled_dir)
  File "dcc.py", line 242, in copy_compiled_libs
    raise Exception("ABI %s is not supported!" % abi)
Exception: ABI x86_64 is not supported!

按照大佬你的建议，修改Application.mk：
APP_ABI := armeabi-v7a arm64-v8a
`# APP_ABI := armeabi-v7a`
还是Exception: ABI x86_64 is not supported!

尝试APP_ABI := all，编译成功，安装到手机可以正常运行..........
打开apk，查看so，arm64-v8a armeabi armeabi-v7a x86 x86_64都有。
？？？？
这是bug吗？

尝试APP_ABI := armeabi
[WARNING ] androguard.core.api_specific_resources: Requested API level 29 is larger than maximum we have, returning API level 28 instead.
Android NDK: The armeabi ABI is no longer supported. Use armeabi-v7a.    
Android NDK: NDK Application 'local' targets unknown ABI(s): armeabi    
Android NDK: Please fix the APP_ABI definition in ./jni/Application.mk    
make: Entering directory `/tmp/dcc-project-vwn204eh'
/home/xi/p/android-sdk-linux/ndk/android-ndk-r17c/build/core/setup-app.mk:79: *** Android NDK: Aborting    .  Stop.
make: Leaving directory `/tmp/dcc-project-vwn204eh'
[ERROR   ] dcc: Compile /home/xi/p/dcc/tests/share/Share-v1.0.apk failed!
Traceback (most recent call last):
  File "dcc.py", line 441, in <module>
    dcc_main(infile, filtercfg, outapk, do_compile, project_dir, source_archive)
  File "dcc.py", line 390, in dcc_main
    build_project(project_dir)
  File "dcc.py", line 87, in build_project
    subprocess.check_call([NDKBUILD, '-j%d' % cpu_count(), '-C', project_dir])
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/xi/p/android-sdk-linux/ndk/android-ndk-r17c/ndk-build', '-j8', '-C', '/tmp/dcc-project-vwn204eh']' returned non-zero exit status 2.

尝试APP_ABI := armeabi-v7a
I: Copying original files...
[ERROR   ] dcc: Compile /home/xi/p/dcc/tests/share/Share-v1.0.apk failed!
Traceback (most recent call last):
  File "dcc.py", line 441, in <module>
    dcc_main(infile, filtercfg, outapk, do_compile, project_dir, source_archive)
  File "dcc.py", line 395, in dcc_main
    copy_compiled_libs(project_dir, decompiled_dir)
  File "dcc.py", line 242, in copy_compiled_libs
    raise Exception("ABI %s is not supported!" % abi)
Exception: ABI x86_64 is not supported!

打开dcc.py，定位
![abi](https://user-images.githubusercontent.com/42903751/66110458-67a51400-e5f9-11e9-87d7-2cbb7b57283d.png)
尝试注释代码：
![尝试注释](https://user-images.githubusercontent.com/42903751/66110502-7c81a780-e5f9-11e9-834b-239dc84a2e4b.png)
继续尝试APP_ABI := armeabi-v7a
[ERROR   ] dcc: Compile /home/xi/p/dcc/tests/share/Share-v1.0.apk failed!
Traceback (most recent call last):
  File "dcc.py", line 441, in <module>
    dcc_main(infile, filtercfg, outapk, do_compile, project_dir, source_archive)
  File "dcc.py", line 395, in dcc_main
    copy_compiled_libs(project_dir, decompiled_dir)
  File "dcc.py", line 245, in copy_compiled_libs
    shutil.copy(libnc, dst)
  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/dcc-project-ylgbn5oc/libs/x86_64/libnc.so'

总结：只有APP_ABI := all
查看so，arm64-v8a armeabi armeabi-v7a x86 x86_64都有。
我觉得，这肯定是个bug了，苦笑。

此外，
`# compile method named onCreate, mostly activity's onCreate`
`.*;onCreate\(Landroid/os/Bundle;.*`
.*; ，我上网查了一下，`;`在正则表达式里面应该没有特殊含义。这个应该匹配`任意字符;`，我觉得如果想匹配onCreate方法，应该是`.*onCreate\(Landroid/os/Bundle;.*`，即把这个`;`移除。

emmm，本菜鸟才疏学浅，如果说错了，还请大佬不要介意，哭笑.jpg

**Comment by amimo** [comment]
1.不是bug.新的ndk不支持armeabi.你用"arm64-v8a armeabi-v7a x86 x86_64"试.
2.你的写法会匹配到类名里面的onCreate,仓库里面的写法只匹配方法名.

**Comment by xmhwws** [comment]
尝试APP_ABI := arm64-v8a armeabi-v7a x86 x86_64
正常编译，但多了armeabi这个so....

之前尝试总结（都无法正常编译）：
APP_ABI := armeabi-v7a
APP_ABI := armeabi-v7a arm64-v8a
APP_ABI := armeabi


APP_ABI := all 可以正常编译
查看so，arm64-v8a armeabi armeabi-v7a x86 x86_64都有。

我尝试APP_ABI := armeabi-v7a，只编译armeabi-v7a，但报错
I: Copying original files...
[ERROR   ] dcc: Compile /home/xi/p/dcc/tests/share/Share-v1.0.apk failed!
Traceback (most recent call last):
  File "dcc.py", line 441, in <module>
    dcc_main(infile, filtercfg, outapk, do_compile, project_dir, source_archive)
  File "dcc.py", line 395, in dcc_main
    copy_compiled_libs(project_dir, decompiled_dir)
  File "dcc.py", line 245, in copy_compiled_libs
    shutil.copy(libnc, dst)
  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/dcc-project-6vv47sj6/libs/x86_64/libnc.so'
