### ISSUE TITLE
你好，大佬Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]

### ISSUE THREAD

**Issue by icew4y** [amimo/dcc#40]
apk被处理过后，安装的时候失败
Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]

**Comment by amimo** [comment]
是不是so被压缩了。用zipalign -p重新对齐试试。

**Comment by icew4y** [comment]
> 是不是so被压缩了。用zipalign -p重新对齐试试。

大佬，我解决了，是反编译后打包的时候默认压缩了，我apk重新指定android:extractNativeLibs="true"即可，多谢大佬，回复很快
