### ISSUE TITLE
BUG :多dex情况下 ,DCC只处理classes.dex

### ISSUE THREAD

**Issue by xmhwws** [amimo/dcc#6]
今天测试DCC ,无意中发现它在多dex情况下 ,只处理classes.dex , 不处理classes2.dex ,classes3.dex等dex

测试环境:
ndk-r16b(测试过 , 正常使用)
APP_ABI := armeabi

filter.txt我没瞎改 ,只写了测试类的类名 , 不匹配构造器, 别的每行都注释了

我测试的类 ,1个在classes2.dex , 1个在classes3.dex , 没测试classes.dex类的方法.
DCC输出: `[INFO    ] dcc: no compiled methods`
然后 , 我将classes2.dex和classes.dex名字互换 ,能处理在classes2.dex的那个测试类 , 此时, 仍然没有处理classes3.dex的那个测试类.
然后 , 我将原apk的classes3.dex和classes.dex名字互换 ,能处理在classes3.dex的那个测试类 , 此时, 仍然没有处理classes2.dex的那个测试类.

总结: 在多dex情况下 ,DCC只处理classes.dex

如果需要我测试的apk , 我稍后补上链接.
请大佬核查一下 , 是否有这个bug

**Comment by amimo** [comment]
目前是只处理第一个classes.dex

**Comment by qtfreet00** [comment]
https://github.com/amimo/dcc/blob/f93c72a2ec7efd057b75c2af34614444e64c7ec8/dcc.py#L283 这里就是硬编码的第一个dex的反编译代码啊 这里逻辑改下就行了 @xmhwws

**Comment by xmhwws** [comment]
> https://github.com/amimo/dcc/blob/f93c72a2ec7efd057b75c2af34614444e64c7ec8/dcc.py#L283
> 
> 这里就是硬编码的第一个dex的反编译代码啊 这里逻辑改下就行了 @xmhwws

首先 , 感谢大佬指点@qtfreet00

测试:
未对原文件修改 ,只添加了print输出 , 结果如下:
***************************************os.listdir(decompiled_dir)内容:
['AndroidManifest.xml', 'apktool.yml', 'assets', 'kotlin', 'lib', 'original', 'res', 'resources.arsc', 'smali', 'smali_classes2', 'smali_classes3', 'smali_mthook', 'unknown']
***************************************classes_output内容:
['smali', 'smali_classes2', 'smali_classes3', 'smali_mthook']

可以DCC看到识别出了多dex , 说明修改点不在这儿
事实上 , 输出信息显示 , DCC在进行这一步前 , 就已经处理了class.dex ,并生成了so文件

**Comment by qtfreet00** [comment]
sorry看错，这里是编译不是反编译的地方

**Comment by xmhwws** [comment]
def compile_dex(apkfile, filtercfg):
这个返回处理好的方法代码

这个方法内部的
d = auto_vm(apkfile)
使用Androguard , 从apk里面取classes.dex的数据 , 没有处理多dex

因为之前没用过Androguard , 我还在分析中 , 哭笑

**Comment by amimo** [comment]
auto_vm用APK.get_dex()只取到了第一个dex, 用get_all_dex貌似可以返回所有的dex.
你可以写的compile_all_dex的方法,然后对每个dex调用compile_dex处理.

**Comment by xmhwws** [comment]
> auto_vm用APK.get_dex()只取到了第一个dex, APK.get_all_dex貌似会返回所有的dex.
> 你可以写个compile_all_dex方法,然后对每个dex调用compile_dex处理.

OK , 我用字典实现了多dex处理
今天下午一直死在字典值的类型不对(不是<class 'androguard.core.bytecodes.dvm.DalvikVMFormat'>)上面 , 困扰了我很久.
最后才发现 , 是因为一个小错误引起的........
唉 , o(╥﹏╥)o

测试了3个apk，2个多dex，1个单dex，都可以正常DCC
已PR

**Comment by xmhwws** [comment]
......

![2019-10-10_18-13-32](https://user-images.githubusercontent.com/42903751/66560743-90458480-eb8a-11e9-92eb-423487ec4ea7.png)

**Comment by xmhwws** [comment]
> 你要点Create pull request

怪不得....

现在应该可以了
![image](https://user-images.githubusercontent.com/42903751/66561414-ff6fa880-eb8b-11e9-9b26-394686a420bd.png)

**Comment by amimo** [comment]
multidex支持可尝试使用该分支代码(multidex)[https://github.com/amimo/dcc/tree/multidex].
先关闭issue
