### ISSUE TITLE
这个不能通过定时任务或者脚本去执行嘛？

### ISSUE THREAD

**Issue by SedgeWarbler** [amimo/dcc#60]
我写了个脚本，去执行加固命令
python脚本 sh脚本 php脚本 我都试过了
脚本就执行下面这一条命令
python3 dcc.py your_app.apk -o out.apk

但是应该是执行了，就是最后没有生成out.apk   project-source.zip倒是生成了

**Comment by amimo** [comment]
环境配置问题吧，比如ndk,这些对配置对了吗？具体报什么错？

**Comment by SedgeWarbler** [comment]
没有报错，手动执行脚本就可以
定时任务执行的就不行

**Comment by amimo** [comment]
在脚本里面先设置ndk路径，cd到你能正常运行的工作目录，然后再运行dcc，肯定可以的。

**Comment by SedgeWarbler** [comment]
> 在脚本里面先设置ndk路径，cd到你能正常运行的工作目录，然后再运行dcc，肯定可以的。

![image](https://github.com/amimo/dcc/assets/32641989/447cf3a8-4a62-43e1-b42c-d50954d9bshf35)
sh脚本就只有执行了一条命令

但是此时就是，如果我通过命令行手动去执行脚本，它会生成out.apk
如果是定时任务执行这个脚本，它就不会生成out.apk

定时任务是执行了的，因为我在命令行前后都有加过日志测试

**Comment by SedgeWarbler** [comment]
> 在脚本里面先设置ndk路径，cd到你能正常运行的工作目录，然后再运行dcc，肯定可以的。

![1694659947156](https://github.com/amimo/dcc/assets/32641989/e0ded425-b9ba-4372-883a-e72c58711421)
可以了，修改dcc.cfg  ndk路径为绝对路径就好了
目测应该是定时任务执行的时候是没有找到环境变量的，所以ndk需要手动设置路径

**Comment by SedgeWarbler** [comment]
![image](https://github.com/amimo/dcc/assets/32641989/bf6afb22-de8d-4823-92ba-22afa4e67c62)
想问一下加固的时候这个是什么原因？

**Comment by SedgeWarbler** [comment]
> 在脚本里面先设置ndk路径，cd到你能正常运行的工作目录，然后再运行dcc，肯定可以的。

![image](https://github.com/amimo/dcc/assets/32641989/5c290cf9-9833-4ce6-96fa-2ece08c34808)
想问一下加固的时候出行这个问题是什么原因
