### ISSUE TITLE
转换的方法数比较少怎么解决?

### ISSUE THREAD

**Issue by zhangxy123666** [amimo/dcc#8]
我看了下只是简单的单行语句的dex2c  感觉少了点，怎么处理一下啊，for  if嵌套的语句如何支持呢？

**Comment by amimo** [comment]
> 我看了下只是简单的单行语句的dex2c 感觉少了点，怎么处理一下啊

什么意思?
dcc默认配置只转化Activity.onCreate,转其他方法需要修改filter.txt文件.


> for if嵌套的语句如何支持呢？

都支持
